[package]
name = "solutions"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "solutions"
path = "src/lib.rs"

[dependencies]
inventory = "0.3"
aoc-macros = { path = "../aoc-macros" }
aoc-core = { path = "../aoc-core" }
